project:
  type: website

website:
  title: "cd ~/sweep.sh/website"

  navbar:
    search: true

    left:
      - learn.qmd
      - blog.qmd
      - about.qmd

    tools:
      - icon: linkedin
        href: https://linkedin.com/noah-shreve
      - icon: github
        href: https://github.com/n-sweep
      - icon: code-slash
        href: https://github.com/n-sweep/n-sweep.github.io

format:

  html:

    theme:
      dark: darkly
      light: flatly

    css: styles.css
    toc: true



