project:
  type: website

website:
  title: "~/"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: linkedin
        href: https://linkedin.com/noah-shreve
      - icon: github
        href: https://github.com/n-sweep/n-swee.github.io

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



